Gustavo e Rogenes - Modo infinito e tela de ranking #66
fegemo/cefet-games-meow-au pull request #100
Opened 2017-11-17 10:50 UTC by GHMarques

2017-11-17 10:52 UTC, GHMarques commented
![](https://github.trello.services/images/mini-trello-icon.png) [#66 Modo infinito e tela de ranking (1ª sprint)](https://trello.com/c/6sqp6zy3/33-66-modo-infinito-e-tela-de-ranking-1-sprint)

2017-11-17 18:19 UTC, fegemo requested changes
Conflitos no _pull request_ estão desfazendo funcionalidades do mundo de jogo.

2017-11-17 18:19 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +            sequencer = new GameSequencer(6, new HashSet<MiniGameFactory>(
@GHMarques e @Rogenes o _pull request_ contém vários conflitos porque está desfazendo parte do trabalho que foi feito na estória de criar o "modo campanha" (tela `OverworldScreen`).

Como vocês entregaram a estória de _ranking_ depois da estória do mundo de jogo, fica com vocês a resolução de conflitos. Vocês conseguem resolver os conflitos mantendo as duas funcionalidades?

2017-11-20 14:21 UTC, merged

2017-11-20 14:24 UTC, fegemo commented
@GHMarques e @Rogenes _pull request_ recebido e mesclado com sucesso! Fiz alguns ajustes em cima dos seus commits: https://github.com/fegemo/cefet-games-meow-au/commit/216ff20c42fa5644aee80b2dd0b5e0e77e2bc9f3, https://github.com/fegemo/cefet-games-meow-au/commit/5cdb62beb660f9476ff6d81098e0041c06e66904, https://github.com/fegemo/cefet-games-meow-au/commit/f12582e6c7ee5b2d5f69167df17a877e2817a3a2, https://github.com/fegemo/cefet-games-meow-au/commit/7482263f0baaa32cfe8d83fa4e8948d6cdeb5f28.