Bug crítico do MouseAttack arrumado
fegemo/cefet-games-meow-au pull request #107
Opened 2017-11-22 00:09 UTC by natyiassanori

2017-11-22 00:11 UTC, natyiassanori commented
![](https://github.trello.services/images/mini-trello-icon.png) [#30 Consertar o MiniGame MouseAttack](https://trello.com/c/W35mbWtp/12-30-consertar-o-minigame-mouseattack)

2017-11-22 03:35 UTC, fegemo requested changes
@natyiassanori e @GabrielMelo96 o pull request contém alterações que desfazem várias coisas feitas por outros alunos. Possivelmente vocês tiveram conflitos ao atualizar o fork de vocês e, na resolução, optaram por ficar com a versão de vocês para todos os conflitos, sem avaliar o conflito com carinho.

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> -import br.cefetmg.games.graphics.hud.SoundIcon;
Este pull request contém commits que estão desfazendo coisas que foram feitas por outros alunos (eg, o ícone de habilitar/desabilitar o som)

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> +        background = new TextureRegion(new Texture("menu/menu-background.png"));
Esta alteração está desfazendo: funcionalidade de pré-carregar os assets do menu usando o assetManager.

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> +     //   background.getTexture().setWrap(
Reintroduzindo código comentado que já havia sido removido.

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> -    protected void assetsLoaded() {
A remoção deste método fez com que o jogo não compilasse mais.

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> -                    transitionScreen(new RankingScreen(super.game, this),
Removeu a tela de ranking.

2017-11-22 03:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> +                    System.exit(0);
O jeito certo de fechar o jogo é `Gdx.app.exit()`, e não `System.exit(0)` - eu havia corrigido isso.

2017-11-22 12:10 UTC, natyiassanori commented
Olá professor @fegemo , realmente foi erro meu, o fork não estava atualizado. Você pode me dizer como faço as alterações? Porque pra mim aparece apenas o arquivo JetRat dando conflito e eu já arrumei. Para arrumar os conflitos que você citou eu altero os arquivos diretamente e faço o commit?

2017-11-22 13:36 UTC, natyiassanori commented
Atualizei os arquivos com as mudanças pedidas.

2017-11-24 19:35 UTC, fegemo commented
@natyiassanori e @GabrielMelo96 pull request mesclado. Precisei fazer um commit de ajuste na tela de créditos (https://github.com/fegemo/cefet-games-meow-au/commit/9b685da43332857891b9ec7309dd4181a4048e6b) e outros no MouseAttack (https://github.com/fegemo/cefet-games-meow-au/commit/f90f82845b68ebb1477580beaf6b217fa5947b47, https://github.com/fegemo/cefet-games-meow-au/commit/b896e978e19715277abd42b8478e76168adf1f43 e https://github.com/fegemo/cefet-games-meow-au/commit/a0e34dea90a293518c2ace8d1758bfec285035de).

A tela de _splash_ poderia ter um botão para voltar para a tela de menu, em vez de forçar o usuário a assistir todos os créditos. Mas aceitei o pull request porque ele está meio atrasado.

2017-11-24 19:35 UTC, closed without merging