Consertar MiniGame CannonCat #37
fegemo/cefet-games-meow-au pull request #109
Opened 2017-11-22 00:27 UTC by Candrade175

_Pull request_ referente à estória #37.

2017-11-22 00:27 UTC, Candrade175 commented
![](https://github.trello.services/images/mini-trello-icon.png) [#37 Consertar MiniGame CannonCat](https://trello.com/c/cNYR8zMb/16-37-consertar-minigame-cannoncat)

2017-11-22 04:40 UTC, fegemo requested changes
@Candrade175 a posição dos gatinhos de fato foi corrigida. Contudo, ainda tem um problema crítico e tenho algumas sugestões:
- crítico: a música não pára quando o jogador perde/ganha, ao término do minigame
- sugestão: como é um canhão, acho que o projétil deveria ser bem mais rápido, menor (sprite.setScale(0.25f), por exemplo) e deveria sair da boca do canhão

2017-11-23 01:11 UTC, Candrade175 commented on core/src/br/cefetmg/games/minigames/CannonCat.java
> +        backgroundMusic.stop();
@fegemo, eu não estou tendo o bug crítico que você comentou sobre "a música não para após o jogo acabar". No meu jogo a música está parando como esperado.

2017-11-23 02:13 UTC, Candrade175 commented
@fegemo, _commit_ realizado com as alterações listadas acima:
- Faltou realmente parar a música quando o tempo acaba. Resolvi isso com a função _onEnd()_
- Com relação ao projétil, eu fiz as modificações sugeridas. Tive que adicionar o ponto de "origem" da boca do canhão para cada textura, devido à forma como está implementado.

2017-11-24 20:06 UTC, merged

2017-11-24 20:06 UTC, fegemo commented
@Candrade175 e @gustavojordao, pull request mesclado!