Pull Request final do click Find q ta terminado
fegemo/cefet-games-meow-au pull request #119
Opened 2017-11-30 14:32 UTC by afa7789

2017-11-30 16:58 UTC, afa7789 commented
![](https://github.trello.services/images/mini-trello-icon.png) [#18 Consertar o MiniGame ClickFindCat](https://trello.com/c/VYzxTbpj/7-18-consertar-o-minigame-clickfindcat)

2017-12-01 15:59 UTC, fegemo requested changes
@afa7789 verificar os problemas identificados na revisão.

2017-12-01 15:59 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ClickFindCat.java
> +        for (Rat Rato : ratos) {
Nome de variável em maiúsculas :(((

2017-12-01 15:59 UTC, fegemo commented on core/assets/data/ProgressFile.txt
> +<<<<<<< HEAD
Arquivo com conflitos não resolvidos...

2017-12-01 15:59 UTC, fegemo commented on .gitignore
> +<<<<<<< HEAD
Arquivo com conflitos não resolvidos...

2017-12-01 15:59 UTC, fegemo commented on core/src/br/cefetmg/games/screens/OverworldScreen.java
> +//<<<<<<< refs/remotes/fegemo/master
Arquivo com conflitos não resolvidos...

2017-12-01 19:18 UTC, afa7789 commented
Vou resolver esses conflitos já já , não tinha visto esses apesar de ter
olhado :/

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-01 13:59 GMT-02:00 Flávio Coutinho <notifications@github.com>:

> *@fegemo* requested changes on this pull request.
>
> @afa7789 <https://github.com/afa7789> verificar os problemas
> identificados na revisão.
> ------------------------------
>
> In core/src/br/cefetmg/games/minigames/ClickFindCat.java
> <https://github.com/fegemo/cefet-games-meow-au/pull/119#discussion_r154379486>
> :
>
> >
> +    public void checkCatRatDistance() {
> +        for (Rat Rato : ratos) {
>
> Nome de variável em maiúsculas :(((
> ------------------------------
>
> In core/assets/data/ProgressFile.txt
> <https://github.com/fegemo/cefet-games-meow-au/pull/119#discussion_r154379544>
> :
>
> > @@ -0,0 +1,9 @@
> +<<<<<<< HEAD
>
> Arquivo com conflitos não resolvidos...
> ------------------------------
>
> In .gitignore
> <https://github.com/fegemo/cefet-games-meow-au/pull/119#discussion_r154379605>
> :
>
> > @@ -70,8 +70,19 @@ build/
>  .DS_Store
>  Thumbs.db
>
> +
> +core/assets/data/ProgressFile\.txt
> +
> +*.txt
> +<<<<<<< HEAD
>
> Arquivo com conflitos não resolvidos...
> ------------------------------
>
> In core/src/br/cefetmg/games/screens/OverworldScreen.java
> <https://github.com/fegemo/cefet-games-meow-au/pull/119#discussion_r154379844>
> :
>
> > @@ -288,6 +288,23 @@ protected void assetsLoaded() {
>              cadeado.setScale(0.5f);
>              i++;
>          }
> +//<<<<<<< refs/remotes/fegemo/master
>
> Arquivo com conflitos não resolvidos...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fegemo/cefet-games-meow-au/pull/119#pullrequestreview-80537982>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZpGF8J6BI1Ivb4WGSFTvrX5lj4VoZVmks5s8CJFgaJpZM4Qwo4r>
> .
>

2017-12-01 23:06 UTC, pbelisario commented on core/src/br/cefetmg/games/screens/OverworldScreen.java
> +//<<<<<<< refs/remotes/fegemo/master
Esse erro eu não encontrei o que deveria ser atualizado, no netBeans não há nada sinalizado, e a execução foi normal

2017-12-01 23:07 UTC, afa7789 commented
Acha que agora foi Coutinho

2017-12-01 23:12 UTC, pbelisario commented on core/src/br/cefetmg/games/screens/OverworldScreen.java
> +//<<<<<<< refs/remotes/fegemo/master
Mentira, tinha corrigido ele em "modo automático"

2017-12-04 15:55 UTC, merged

2017-12-04 15:55 UTC, fegemo commented
@afa7789 pull request recebido