Gustavo Jordão & Cassiano Andrade
fegemo/cefet-games-meow-au pull request #7
Opened 2017-09-17 21:00 UTC by Candrade175

O relatório a respeito dos minigames foi feito no arquivo README.

2017-09-20 19:53 UTC, fegemo requested changes
Pessoal, vejam os itens da revisão. Corrijam fazendo um novo commit no branch, atualizando o pull request, ou fechem este e reabram um novo com tudo certo.

2017-09-20 19:53 UTC, fegemo commented on README.md
> +## Jogos implementados
Pessoal, vocês alteraram o README.md na raiz do projeto. Não posso aceitar o pull request assim.

2017-09-20 19:53 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/JumpTheObstacles.java
> + * @author fegemo <coutinho@decom.cefetmg.br>
Eu que fiz??? =)

2017-09-20 19:53 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ticCatDog/Move.java
> +public class Move
Em vez de criar novos pacotes para os minigames, como essas classes são exclusivas de 1 minigame, peço que coloquem como classes internas do respectivo minigame.

2017-09-20 19:53 UTC, fegemo commented on core/src/br/cefetmg/games/screens/MenuScreen.java
> +
Não alterar arquivos fora dos minigames que foram criados (e a PlayingGamesScreen para inclui-los).

2017-09-20 19:53 UTC, fegemo commented on gradlew.bat
> -@if "%DEBUG%" == "" @echo off
Por que este arquivo foi alterado?

2017-09-20 19:53 UTC, fegemo commented on html/build.gradle
> -apply plugin: "java"
Este também não deveria ter sido alterado.

2017-09-20 19:53 UTC, fegemo commented on html/src/br/cefetmg/games/GdxDefinition.gwt.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Idem

2017-09-20 19:53 UTC, fegemo commented on html/src/br/cefetmg/games/GdxDefinitionSuperdev.gwt.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Idem

2017-09-20 19:53 UTC, fegemo commented on html/src/br/cefetmg/games/client/HtmlLauncher.java
> -package br.cefetmg.games.client;
Idem

2017-09-21 04:07 UTC, Candrade175 commented
Professor, atualizamos o _pull request_ (pelo menos esta foi a expectativa).

A única questão que vimos foi que continua sendo apontando que há diferença no arquivo README.md mesmo tendo nenhuma. Atualizamos o nosso README.md local por meio do _upstream_ e mesmo assim estamos tendo esta questão.

Acreditamos que os demais itens foram resolvidos com êxito.

2017-09-25 23:22 UTC, fegemo approved these changes

2017-09-26 00:53 UTC, merged

2017-10-03 12:43 UTC, fegemo commented
**Correção** para @gustavojordao e @Candrade175 

Sobre o código e a entrega: 10%

Fiz alguns commits de ajuste:
- https://github.com/fegemo/cefet-games-meow-au/commit/909319f7296819b42bb545aa6cf1f5b7fe552e29
- https://github.com/fegemo/cefet-games-meow-au/commit/7024182401d484b2048e2b014a63fd7fb09a5040
- https://github.com/fegemo/cefet-games-meow-au/commit/825689d4a39f7df019a35d7b9b6812408f86011f
- https://github.com/fegemo/cefet-games-meow-au/commit/fd06f6ed9f9c3a5162616a14063f15c342da3b10
- https://github.com/fegemo/cefet-games-meow-au/commit/669a326c9d031ebd36d2e12ae73812a86119f355

Característica SuperPremium: 10%
(+10%) pelo MiniMax

MiniGame 1: Funcionamento básico: 14%
(-3%) imagens distorcidas devido à perda de razão de aspecto

MiniGame 1: Dificuldade variável: 0
(-8%) a dificuldade é a mesma sempre (porque difficulty está entre [0, 1]). Fazer o gato começar a partir de 0.5 é uma boa, assim como diminuir o tempo para pensar. Apenas sugiro fazer esta última alteração de forma linear em vez da forma como você tentou fazer. Além disso, é importante que, em dificuldades baixas (e.g., < 0,2), em vez de chamar o MiniMax, o gato jogue aleatoriamente.

MiniGame 1: Independência de resolução: 5%

MiniGame 1: Input correto: 5%

MiniGame 1: Estilo próprio: 3%
(-2%) está um pouco difícil reconhecer os "símbolos" (bola, x) porque as imagens do gato e do cachorro de óculos possuem detalhes demais (acho que é isso). Talvez seja mais interessante usar desenhos mais simples de um cão e um gato.

MiniGame 2: Funcionamento básico: 7%
(-3%) o doge e os cannonballs estão muito abaixo na tela e a HUD acaba atrapalhando um pouco. Sugiro subir os personagens um pouco, para que fiquem acima da HUD.
(-2%) a spritesheet do doge está com os pixels na borda esbranquiçados em vez de semitransparentes.
(-3%) doge faz animação de lambendo parado enquanto está pulando
(-2%) cannonballs surgem do nada e do meio da tela (seria melhor se viessem do canto)

MiniGame 2: Dificuldade variável: 6%
(-2%) alterar apenas o spawnInterval e a velocidade deu pouca variabilidade ao minigame

MiniGame 2: Independência de resolução: 5%

MiniGame 2: Input correto: 3%
(-2%) o efeito do pulo sem gravidade ficou estranho. Pra fazer gravidade, é bem simples, basta definir uma velocidade alta para cima quando salta e, a cada atualização, soma uma forcinha constante para baixo na velocidade.

MiniGame 2: Estilo próprio: 5%

Extra: Diversão e Criatividade: 3%
(+3%) pela criatividade do TicCatDog

Extra: Harmonia: 3%
(+3%) pela qualidade da implementação

Percentual de atraso: 0

Nota Porcentual: 79.00%
Nota Final: 11.85