#72 Tela de loading para entrar na sequência de MiniGames
fegemo/cefet-games-meow-au pull request #83
Opened 2017-11-08 00:29 UTC by Candrade175

Eu fiz uma tela de _loading_ básica como descrito na atividade #72.

Tomando como base o [tutorial](http://www.coding-daddy.xyz/node/23) e o seu respectivo [código](https://github.com/serhiy/libgdx-circular-cooldown), a tela de _loading_ consiste em um círculo que é preenchido de acordo com o retorno de _assets.getProgress()_. Somente após o preenchimento completo do círculo é que a _BaseScreen.draw()_ é autorizada (por meio da booleana _isLoadingOver_) a continuar seu processamento.

2017-11-08 14:12 UTC, fegemo requested changes
@Candrade175 e @gustavojordao, preciso que vocês revejam o _pull request_.
Eu executei aqui e a tela está aparecendo apenas antes da tela de _splash_. A imagem de fundo está aparecendo cortada também (dá pra ver a metade da esquerda dela apenas). E não enxerguei a barra de progresso também.

Eu entendi que a implementação que vocês fizeram, na `BaseScreen`, tem o objetivo de funcionar para todas as telas. Contudo, esta estória pedia para que ela aparecesse apenas na hora de entrar na sequência de MiniGames (vide o nome da estória): vejam o método _preload_ da classe `PlayingGamesScreen`.

Além disso, a barra de progresso que vi no tutorial que você usou tem um artefato visual ruim ocasionado pela instabilidade dos pixels já desenhados do arco, além da impossibilidade (creio eu) de se fazer _anti-aliasing_¹ devido ao uso do Pixmap.

¹ aliasing é o problema da imagem ficar "serrilhada"

2017-11-08 14:12 UTC, fegemo commented on core/src/br/cefetmg/games/screens/BaseScreen.java
> +            if (wasJustDisposed)
@Candrade175 e @gustavojordao, em termos de Engenharia de Software, é importante sempre usar chaves para criar um bloco mesmo quando temos apenas uma instrução dentro de um if/else/for/while. Vejam esta [resposta no StackOverflow com os motivos](https://stackoverflow.com/a/12193202/1783793).

2017-11-08 14:12 UTC, fegemo commented on core/src/br/cefetmg/games/screens/LoadingScreen.java
> +            try {
Não vi a necessidade para este bloco try/finally

2017-11-09 02:33 UTC, Candrade175 commented
@fegemo, inicialmente resetei o arquivo `BaseScreen` para a versão _upstream_ e iniciei a implementação em `PlayingGamesScreen` como sugerido. Entretanto, eu percebi por meio de testes que as funções _update_, _draw_ e _preload_ desta classe só eram chamadas **após** todos os _assets_ terem sido carregados, o que inviabilizou a chamada da tela de carregamento. Não enxerguei uma forma de fazer o carregamento por meio desta classe :-(

Com isso, eu retornei para a `BaseScreen` e fiz com que a tela de carregamento só fosse chamada quando a Game.Screen atual fosse referente à "PlayingGamesScreen". 

Quanto ao que vc disse sobre "artefato visual ruim ocasionado pela instabilidade dos pixels", eu concordo. Realmente o círculo fica serrilhado. Posso pesquisar e aprimorar esta barra de progresso, tudo bem?

2017-11-15 01:17 UTC, closed without merging